import _ from '@lodash';
import mock from '../mock';

const activityAppDB = {
	products: [
		{
			id: '1',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '2',
			clientName: 'B Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 11,
		},
		{
			id: '3',
			clientName: 'C Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '4',
			name: 'First Snow - Canvas Print',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '5',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '6',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '7',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '8',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '9',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '10',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '11',
			name: 'A Walk Amongst Friends - Canvas Print',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '12',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '13',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},
		{
			id: '14',
			clientName: 'A Walk Amongst Friends - Canvas Print',
			description: 'Lexus',
			writtenDate: '10/09/20',
			issuedDate: '10/09/20',
			productLine: 'Auto',			
			productType: 'Add On',
			sourceOfBusiness: 'Multiline Review',
			productDollars: 943,
			bonus: 9.43,
			monthWritten: 10,
			monthIssued: 10,
		},	
	],
};

mock.onGet('/api/activity-app/products').reply(() => {
	return [200, activityAppDB.products];
});



