import mock from '../mock';

const productioAppDB = {
	widgets: [
		{
			id: 'IndividualSalesGoalsChat',
			title: "INDIVIDUAL Sales Goals vs Actual Production",
			ranges: {
				TW: 'As A Team',
				IN: 'Individually',
				IC: 'Include Initial Bonus',
				DI: "Don't Include Initial Bonus"
			},
			mainChart: {
				TW: {
					
					labels: [],
					datasets: [
						{
							type: 'bar',
							barPercentage: 0.5,
							label: 'Sales Goal',
							data: [ 20, 25, 22, 12],
							backgroundColor: '#42BFF7',
							hoverBackgroundColor: '#87CDF7',
							categoryPercentage: 1,
						},
						{
							type: 'bar',
							barPercentage: 0.5,
							label: 'Actual Sales',
							data: [11, 8, 10, 50],
							backgroundColor: '#C6ECFD',
							hoverBackgroundColor: '#D7EFFD',
							categoryPercentage: 1
						},										
					]
				},
				options: {
					responsive: true,
					maintainAspectRatio: false,
					legend: {
						display: true,
						position: 'bottom'
					},
					tooltips: {
						mode: 'label'
					},
					scales: {
						xAxes: [
							{
								stacked: true,
								display: true,
								gridLines: {
									display: true
								},
								labels: ['Fire', 'Life', 'Health', 'Bank']
							}
						],
						yAxes: [
							{
								stacked: true,
								type: 'linear',
								display: true,
								position: 'left',
								gridLines: {
									display: true
								},
								labels: {
									show: true
								}
							}
						]
					}
				}
			},
			
		},
		{
			id: 'TeamSalesGoalsChat',
			title: "TEAM Sales Goals vs Actual Production",
			ranges: {
				TW: 'As A Team',
				IN: 'Individually',
				IC: 'Include Initial Bonus',
				DI: "Don't Include Initial Bonus"
			},
			mainChart: {
				TW: {
					
					labels: [],
					datasets: [
						{
							type: 'bar',
							barPercentage: 0.5,
							label: 'Sales Goal',
							data: [ 20, 25, 22, 12],
							backgroundColor: '#42BFF7',
							hoverBackgroundColor: '#87CDF7',
							categoryPercentage: 1,
						},
						{
							type: 'bar',
							barPercentage: 0.5,
							label: 'Actual Sales',
							data: [11, 8, 10, 50],
							backgroundColor: '#C6ECFD',
							hoverBackgroundColor: '#D7EFFD',
							categoryPercentage: 1
						},										
					]
				},
				options: {
					responsive: true,
					maintainAspectRatio: false,
					legend: {
						display: true,
						position: 'bottom'
					},
					tooltips: {
						mode: 'label'
					},
					scales: {
						xAxes: [
							{
								stacked: true,
								display: true,
								gridLines: {
									display: true
								},
								labels: ['Fire', 'Life', 'Health', 'Bank']
							}
						],
						yAxes: [
							{
								stacked: true,
								type: 'linear',
								display: true,
								position: 'left',
								gridLines: {
									display: true
								},
								labels: {
									show: true
								}
							}
						]
					}
				}
			},
			
		},
		{
			id: 'WrttenSalesResultsReportChat',
			title: "WRITTEN SALES ACTIVITY BY MONTH",
			ranges: {
				TW: 'As A Team',
				IN: 'Individually',
				IC: 'Include Initial Bonus',
				DI: "Don't Include Initial Bonus"
			},
			mainChart: {
				TW: {
					
					labels: [],
					datasets: [
						{
							type: 'bar',
							barPercentage: 0.5,
							label: 'Auto Policies',
							data: [ 20, 25, 22, 12, 12, 50, 45, 7, 8, 10, 56, 22],
							backgroundColor: '#42BFF7',
							hoverBackgroundColor: '#87CDF7',
							categoryPercentage: 1,
						},
						{
							type: 'bar',
							barPercentage: 0.5,
							label: 'Fire Policies',
							data: [11, 8, 10, 50, 45, 7, 8, 10, 17, 45, 56, 22],
							backgroundColor: '#C6ECFD',
							hoverBackgroundColor: '#D7EFFD',
							categoryPercentage: 1
						},
						{
							type: 'bar',
							label: 'Life Policies',
							barPercentage: 0.5,
							data: [45, 7, 8, 10, 17, 45, 76, 23, 77, 31, 56, 22],
							backgroundColor: '#f9cfcf',
							hoverBackgroundColor: '#ffcece',
							categoryPercentage: 1
						},
						{
							type: 'bar',
							label: 'Health Policies',
							barPercentage: 0.5,
							data: [67, 34, 34, 20, 25, 34, 20, 25, 56, 22, 56, 22],
							backgroundColor: '#77ff99',
							hoverBackgroundColor: '#c9ffd6',
							categoryPercentage: 1
						},
						{
							type: 'bar',
							label: 'Bank Products',
							barPercentage: 0.5,
							data: [78, 33, 34, 20, 25, 56, 22, 45, 76, 23, 77, 31],
							backgroundColor: '#92dafc',
							hoverBackgroundColor: '#d1eefc',
							categoryPercentage: 1
						},						
					]
				},
				options: {
					responsive: true,
					maintainAspectRatio: false,
					legend: {
						display: true,
						position: 'bottom'
					},
					tooltips: {
						mode: 'label'
					},
					scales: {
						xAxes: [
							{
								stacked: true,
								display: true,
								gridLines: {
									display: true
								},
								labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
							}
						],
						yAxes: [
							{
								stacked: true,
								type: 'linear',
								display: true,
								position: 'left',
								gridLines: {
									display: true
								},
								labels: {
									show: true
								}
							}
						]
					}
				}
			},
		},
		{
			id: 'IssuedSalesResultsReportChat',
			title: "ISSUED SALES ACTIVITY BY MONTH",
			ranges: {
				TW: 'As A Team',
				IN: 'Individually',
				IC: 'Include Initial Bonus',
				DI: "Don't Include Initial Bonus"
			},
			mainChart: {
				TW: {
					
					labels: [],
					datasets: [
						{
							type: 'bar',
							barPercentage: 0.5,
							label: 'Auto Policies',
							data: [ 20, 25, 22, 12, 12, 50, 45, 7, 8, 10, 56, 22],
							backgroundColor: '#42BFF7',
							hoverBackgroundColor: '#87CDF7',
							categoryPercentage: 1,
						},
						{
							type: 'bar',
							barPercentage: 0.5,
							label: 'Fire Policies',
							data: [11, 8, 10, 50, 45, 7, 8, 10, 17, 45, 56, 22],
							backgroundColor: '#C6ECFD',
							hoverBackgroundColor: '#D7EFFD',
							categoryPercentage: 1
						},
						{
							type: 'bar',
							label: 'Life Policies',
							barPercentage: 0.5,
							data: [45, 7, 8, 10, 17, 45, 76, 23, 77, 31, 56, 22],
							backgroundColor: '#f9cfcf',
							hoverBackgroundColor: '#ffcece',
							categoryPercentage: 1
						},
						{
							type: 'bar',
							label: 'Health Policies',
							barPercentage: 0.5,
							data: [67, 34, 34, 20, 25, 34, 20, 25, 56, 22, 56, 22],
							backgroundColor: '#77ff99',
							hoverBackgroundColor: '#c9ffd6',
							categoryPercentage: 1
						},
						{
							type: 'bar',
							label: 'Bank Products',
							barPercentage: 0.5,
							data: [78, 33, 34, 20, 25, 56, 22, 45, 76, 23, 77, 31],
							backgroundColor: '#92dafc',
							hoverBackgroundColor: '#d1eefc',
							categoryPercentage: 1
						},						
					]
				},
				options: {
					responsive: true,
					maintainAspectRatio: false,
					legend: {
						display: true,
						position: 'bottom'
					},
					tooltips: {
						mode: 'label'
					},
					scales: {
						xAxes: [
							{
								stacked: true,
								display: true,
								gridLines: {
									display: true
								},
								labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
							}
						],
						yAxes: [
							{
								stacked: true,
								type: 'linear',
								display: true,
								position: 'left',
								gridLines: {
									display: true
								},
								labels: {
									show: true
								}
							}
						]
					}
				}
			},
		},
		{
			id: 'ProductPieChat',
			title: 'Budget Distribution',
			mainChart: {
				labels: ['Auto', 'Fire', 'Life', 'Health', 'Bank'],
				datasets: [
					{
						data: [12, 17, 28, 25, 15],
						backgroundColor: ['#F44336', '#9C27B0', '#03A9F4', '#E91E63', '#FFC107'],
						hoverBackgroundColor: ['#F45A4D', '#A041B0', '#25B6F4', '#E9487F', '#FFD341']
					}
				],
				options: {
					cutoutPercentage: 0,
					spanGaps: false,
					legend: {
						display: true,
						position: 'bottom',
						labels: {
							padding: 16,
							usePointStyle: true
						}
					},
					maintainAspectRatio: false
				}
			}
		},
		{
			id: 'BonusPieChat',
			title: 'Budget Distribution',
			mainChart: {
				labels: ['Auto', 'Fire', 'Life', 'Health', 'Bank'],
				datasets: [
					{
						data: [12, 17, 28, 25, 15],
						backgroundColor: ['#F44336', '#9C27B0', '#03A9F4', '#E91E63', '#FFC107'],
						hoverBackgroundColor: ['#F45A4D', '#A041B0', '#25B6F4', '#E9487F', '#FFD341']
					}
				],
				options: {
					cutoutPercentage: 0,
					spanGaps: false,
					legend: {
						display: true,
						position: 'bottom',
						labels: {
							padding: 16,
							usePointStyle: true
						}
					},
					maintainAspectRatio: false
				}
			}
		},
		{
			id: 'WrttenSalesResultsReportTable',
			title: 'Team Members',
			table: {
				columns: [],
				rows: [],
				headers: [],
				tableContent : {
					January:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					February:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					March:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					April:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					May:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					June:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					July:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					August:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					September:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					October:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					November:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					December:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					Quarter_1_Totals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					Quarter_2_Totals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					Quarter_3_Totals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					Quarter_4_Totals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					AnnualTotals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					ProjectedForYear:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					}					
				},
			}
		},
		{
			id: 'IssuedSalesResultsReportTable',
			title: 'Team Members',
			table: {
				columns: [],
				rows: [],
				headers: [],
				tableContent : {
					January:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					February:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					March:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					April:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					May:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					June:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					July:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					August:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					September:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					October:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					November:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					December:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					Quarter_1_Totals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					Quarter_2_Totals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					Quarter_3_Totals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					Quarter_4_Totals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					AnnualTotals:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					},
					ProjectedForYear:{
						autoPolicies:'-',
						autoPremium:'-',
						firePolicies:'-',
						firePremium:'-',
						lifePolicies:'-',
						lifePremium:'-',
						healthPolicies:'-',
						healthPremium:'-',
						bankProducts:'-',
						bankDollars:'-',					
						totalProducts:'-',
						totalPremium:'-',
					}					
				},
			}
		},
		{
			id: 'productionLineTable1',
			title: 'Team Members',
			table: {
				columns: [
					{
						id: 'avatar',
						title: 'Month',
						color: '',
						align: 'center',
						colSpan: 1,
						rowSpan: 2
					},
					{
						id: 'policiesAndPremium',
						title: 'Policies & Premium',
						color: 'bg-green-300',
						colSpan: 3
					},
					{
						id: 'policySalesByPolicyType',
						title: 'POLICY SALES by Policy Type',
						color: 'bg-yellow-500',
						colSpan: 13
					},
					// {
					// 	id: 'policySalesBySourcesBusiness',
					// 	title: 'POLICY SALES by Sources of Business',
					// 	color: 'bg-indigo-200',
					// 	colSpan: 20
					// },					
				],
				rows: [],
				headers: [],
				tableContent : {
					January:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					February:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					March:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					April:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					May:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					June:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					July:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					August:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					September:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					October:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					November:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					December:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					Quarter_1_Totals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					Quarter_2_Totals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					Quarter_3_Totals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					Quarter_4_Totals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					AnnualTotals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					ProjectedForYear:{
						// autoPolicies:'-',
						// autoPremium:'-',
						// firePolicies:'-',
						// firePremium:'-',
						// lifePolicies:'-',
						// lifePremium:'-',
						// healthPolicies:'-',
						// healthPremium:'-',
						// bankProducts:'-',
						// bankDollars:'-',					
						// totalProducts:'-',
						// totalPremium:'-',
						averagePremium:'-',
						numberOfPolicies:'-',
						policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					}					
				},
			}
		},
		{
			id: 'productionLineTable2',
			title: 'Team Members',
			table: {
				columns: [
					{
						id: 'avatar',
						title: 'Month',
						color: '',
						align: 'center',
						colSpan: 1,
						rowSpan: 2
					},
					{
						id: 'policiesAndPremium',
						title: 'Policies & Premium',
						color: 'bg-green-300',
						colSpan: 3
					},
					// {
					// 	id: 'policySalesByPolicyType',
					// 	title: 'POLICY SALES by Policy Type',
					// 	color: 'bg-yellow-500',
					// 	colSpan: 13
					// },
					{
						id: 'policySalesBySourcesBusiness',
						title: 'POLICY SALES by Sources of Business',
						color: 'bg-indigo-200',
						colSpan: 20
					},					
				],
				rows: [],
				headers: [],
				tableContent : {
					January:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					February:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					March:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					April:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					May:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					June:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					July:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					August:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					September:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					October:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					November:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					December:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Quarter_1_Totals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Quarter_2_Totals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Quarter_3_Totals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Quarter_4_Totals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					AnnualTotals:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					ProjectedForYear:{
						averagePremium:'-',
						numberOfPolicies:'-',
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					}					
				},
			}
		},
		{
			id: 'productionLineTable3',
			title: 'Team Members',
			table: {
				columns: [
					{
						id: 'avatar',
						title: 'Month',
						color: '',
						align: 'center',
						colSpan: 1,
						rowSpan: 2
					},
					// {
					// 	id: 'policiesAndPremium',
					// 	title: 'Policies & Premium',
					// 	color: 'bg-green-300',
					// 	colSpan: 3
					// },
					{
						id: 'PremiumSalesByPolicyType',
						title: 'PREMIUM SALES by Policy Type(In Thousands)',
						color: 'bg-yellow-500',
						colSpan: 13
					},
					// {
					// 	id: 'policySalesBySourcesBusiness',
					// 	title: 'POLICY SALES by Sources of Business',
					// 	color: 'bg-indigo-200',
					// 	colSpan: 20
					// },					
				],
				rows: [],
				headers: [],
				tableContent : {
					January:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					February:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					March:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					April:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					May:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					June:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					July:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					August:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					September:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					October:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					November:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					December:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					Quarter_1_Totals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					Quarter_2_Totals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					Quarter_3_Totals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					Quarter_4_Totals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					AnnualTotals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					},
					ProjectedForYear:{						
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// policiPremium:'-',
						personallyProduced:'-',
						rawNew:'-',
						addOn:'-',
						transferIn:'-',
						label1:'-',
						label2:'-',
						label3:'-',
						label4:'-',					
						label5:'-',
						label6:'-',
						label7:'-',
						label8:'-',
						Bonus:'-',
					}					
				},
			}
		},
		{
			id: 'productionLineTable4',
			title: 'Team Members',
			table: {
				columns: [
					{
						id: 'avatar',
						title: 'Month',
						color: '',
						align: 'center',
						colSpan: 1,
						rowSpan: 2
					},
					// {
					// 	id: 'policiesAndPremium',
					// 	title: 'Policies & Premium',
					// 	color: 'bg-green-300',
					// 	colSpan: 3
					// },
					// {
					// 	id: 'policySalesByPolicyType',
					// 	title: 'POLICY SALES by Policy Type',
					// 	color: 'bg-yellow-500',
					// 	colSpan: 13
					// },
					{
						id: 'policySalesBySourcesBusiness',
						title: 'PREMIUM SALES by Sources of Business(In Thousands)',
						color: 'bg-indigo-200',
						colSpan: 20
					},					
				],
				rows: [],
				headers: [],
				tableContent : {
					January:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					February:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					March:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					April:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					May:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					June:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					July:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					August:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					September:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					October:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					November:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					December:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Quarter_1_Totals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Quarter_2_Totals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Quarter_3_Totals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Quarter_4_Totals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					AnnualTotals:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					ProjectedForYear:{
						// averagePremium:'-',
						// numberOfPolicies:'-',
						// centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						networkingMeeting:'-',
						callIn:'-',
						outboundCalling:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					}					
				},
			}
		},
		{
			id: 'IndividualTable',
			title: 'Team Members',
			table: {
				columns: [
					{
						id: 'avatar',
						title: 'GOALS',
						color: '',
						align: 'center',
						rowSpan: 2,
					},
					{
						id: 'individualGoalsAndProduction',
						title: 'Individual Goals and Production',
						color: '',
						colSpan: 4,
					},
				],
				rows: [],
				headers: [],
				tableContent : {
					Auto:{
						salesGoal:'-',
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Fire:{
						salesGoal:'-',
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Life:{
						salesGoal:'-',
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Health:{
						salesGoal:'-',
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Bank:{
						salesGoal:'-',
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Totals:{
						salesGoal:'-',
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},											
				},
			}
		},
		{
			id: 'AgencyTable',
			title: 'Team Members',
			table: {
				columns: [
					{
						id: 'avatar',
						title: 'GOALS',
						color: '',
						align: 'center',
						rowSpan: 2,
					},
					{
						id: 'AgencyGoalsAndProduction',
						title: 'Agency Goals and Production',
						color: '',
						colSpan: 3,
					},
				],
				rows: [],
				headers: [],
				tableContent : {
					Auto:{
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Fire:{
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Life:{
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Health:{
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Bank:{
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},
					Totals:{
						actualSales:'-',
						totalPremium:'-',
						averagePrenium:'-',	
					},											
				},
			}
		},		
		{
			id: 'SourcesOfBonusesTable',
			title: 'Team Members',
			table: {
				columns: [
					{
						id: 'avatar',
						title: 'GOALS',
						color: '',
						align: 'center',
						rowSpan: 2,
					},
					{
						id: '*',
						title: 'Where your Individual Production Came From - Sources of Business',
						color: '',
						colSpan: 20,
					},
				],
				rows: [],
				headers: [],
				tableContent : {
					Auto:{
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						label1:'-',
						label:'-',
						parkBench:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Fire:{
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						label1:'-',
						label:'-',
						parkBench:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Life:{
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						label1:'-',
						label:'-',
						parkBench:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Health:{
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						label1:'-',
						label:'-',
						parkBench:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Bank:{
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						label1:'-',
						label:'-',
						parkBench:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},
					Totals:{
						centerOfInfluences:'-',
						clientRequest:'-',
						directMailLetter:'-',
						internetLead:'-',	
						multilineReview:'-',
						label1:'-',
						label:'-',
						parkBench:'-',
						personalVisit:'-',
						postcard:'-',
						referral:'-',
						salespersonPivot:'-',
						sign:'-',
						television:'-',
						transfer:'-',
						walkIn:'-',
						website:'-',
						webSearch:'-',
						yellowPages:'-',
						other:'-',
					},											
				},
			}
		},		
		{
			id: 'BonusesEarnedThisPeriodTable',
			title: 'Team Members',
			table: {
				columns: [
					{
						id: 'avatar',
						title: 'GOALS',
						color: '',
						align: 'center',
						rowSpan: 2,
					},
					{
						id: 'bonusesEarnedThisPeriod',
						title: 'BONUSES EARNED THIS PERIOD',
						color: '',
						colSpan: 7,
					},
				],
				rows: [],
				headers: [],
				tableContent : {
					Auto:{
						initialItemBonuses:'-',
						individualTargetBonuses:'-',
						teamTargetBonuses:'-',
						policyGrowthBonuses:'-',
						lapseRateBonuses:'-',	
						specialPromotion:'-',	
						totalBonuses:'-',		
					},
					Fire:{
						initialItemBonuses:'-',
						individualTargetBonuses:'-',
						teamTargetBonuses:'-',
						policyGrowthBonuses:'-',
						lapseRateBonuses:'-',	
						specialPromotion:'-',	
						totalBonuses:'-',
					},
					Life:{
						initialItemBonuses:'-',
						individualTargetBonuses:'-',
						teamTargetBonuses:'-',
						policyGrowthBonuses:'-',
						lapseRateBonuses:'-',	
						specialPromotion:'-',	
						totalBonuses:'-',
					},
					Health:{
						initialItemBonuses:'-',
						individualTargetBonuses:'-',
						teamTargetBonuses:'-',
						policyGrowthBonuses:'-',
						lapseRateBonuses:'-',	
						specialPromotion:'-',	
						totalBonuses:'-',
					},
					Bank:{
						initialItemBonuses:'-',
						individualTargetBonuses:'-',
						teamTargetBonuses:'-',
						policyGrowthBonuses:'-',
						lapseRateBonuses:'-',	
						specialPromotion:'-',	
						totalBonuses:'-',
					},
					Totals:{
						initialItemBonuses:'-',
						individualTargetBonuses:'-',
						teamTargetBonuses:'-',
						policyGrowthBonuses:'-',
						lapseRateBonuses:'-',	
						specialPromotion:'-',	
						totalBonuses:'-',
					},											
				},
			}
		},	
	],
	projects: [
		{
			id: 1,
			name: 'ACME Corp. Backend App'
		},
		{
			id: 2,
			name: 'ACME Corp. Frontend App'
		},
		{
			id: 3,
			name: 'Creapond'
		},
		{
			id: 4,
			name: 'Withinpixels'
		}
	]
};

mock.onGet('/api/production-app/widgets').reply(config => {
	return [200, productioAppDB.widgets];
});

mock.onGet('/api/production-app/projects').reply(config => {
	return [200, productioAppDB.projects];
});
