export const fireHeader1 = [
	{ id: 2, value: 'Average Premium', type: true, color: 'bg-green-300' },
	{ id: 3, value: 'Number of Policies', type: true, color: 'bg-green-300' },
	{ id: 4, value: 'Policy Premium', type: true, color: 'bg-green-300' },
	{ id: 5, value: 'Personally Produced', type: true, color: 'bg-yellow-500' },
	{ id: 6, value: 'Raw New', type: true, color: 'bg-yellow-500' },
	{ id: 7, value: 'Client Request', type: true, color: 'bg-yellow-500' },
	{ id: 8, value: 'Transfer In', type: true, color: 'bg-yellow-500' },
	{ id: 9, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 10, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 11, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 12, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 13, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 14, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 15, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 16, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 17, value: 'Bonus', type: true, color: 'bg-yellow-500' },
];

export const fireHeader2 = [
	{ id: 1, value: 'Average Premium', type: true, color: 'bg-green-300' },
	{ id: 2, value: 'Number of Policies', type: true, color: 'bg-green-300' },
	{ id: 3, value: 'Policy Premium', type: true, color: 'bg-green-300' },
	{ id: 4, value: 'Center of Influence', type: true, color: 'bg-indigo-200' },
	{ id: 5, value: 'Client Request', type: true, color: 'bg-indigo-200' },
	{ id: 6, value: 'Direct Mail Letter', type: true, color: 'bg-indigo-200' },
	{ id: 7, value: 'Internet Read >>', type: true, color: 'bg-indigo-200' },
	{ id: 8, value: 'Multiline Review', type: true, color: 'bg-indigo-200' },
	{ id: 9, value: 'Networking Meeting', type: true, color: 'bg-indigo-200' },
	{ id: 10, value: 'Call In', type: true, color: 'bg-indigo-200' },
	{ id: 11, value: 'Outbound Calling', type: true, color: 'bg-indigo-200' },
	{ id: 12, value: 'Personal Visit', type: true, color: 'bg-indigo-200' },
	{ id: 13, value: 'Postcard', type: true, color: 'bg-indigo-200' },
	{ id: 14, value: 'Referral', type: true, color: 'bg-indigo-200' },
	{ id: 15, value: 'Salesperson Pilvot', type: true, color: 'bg-indigo-200' },
	{ id: 16, value: 'Sign', type: true, color: 'bg-indigo-200' },
	{ id: 17, value: 'Television', type: true, color: 'bg-indigo-200' },
	{ id: 18, value: 'Transfer', type: true, color: 'bg-indigo-200' },
	{ id: 19, value: 'Walk-In', type: true, color: 'bg-indigo-200' },
	{ id: 20, value: 'Website', type: true, color: 'bg-indigo-200' },
	{ id: 21, value: 'WebSearch', type: true, color: 'bg-indigo-200' },
	{ id: 22, value: 'Yellow Pages', type: true, color: 'bg-indigo-200' },
	{ id: 23, value: 'Other', type: true, color: 'bg-indigo-200' },
];

export const fireHeader3 = [
	// { id: 2, value: 'Average Premium', type: true, color: 'bg-green-300' },
	// { id: 3, value: 'Number of Policies', type: true, color: 'bg-green-300' },
	// { id: 4, value: 'Policy Premium', type: true, color: 'bg-green-300' },
	{ id: 5, value: 'Personally Produced', type: true, color: 'bg-yellow-500' },
	{ id: 6, value: 'Raw New', type: true, color: 'bg-yellow-500' },
	{ id: 7, value: 'Client Request', type: true, color: 'bg-yellow-500' },
	{ id: 8, value: 'Transfer In', type: true, color: 'bg-yellow-500' },
	{ id: 9, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 10, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 11, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 12, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 13, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 14, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 15, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 16, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 17, value: 'Adjustments', type: true, color: 'bg-yellow-500' },
];

export const fireHeader4 = [
	// { id: 2, value: 'Average Premium', type: true, color: 'bg-green-300' },
	// { id: 3, value: 'Number of Policies', type: true, color: 'bg-green-300' },
	{ id: 4, value: 'Center of Influence', type: true, color: 'bg-green-300' },
	{ id: 5, value: 'Client Request', type: true, color: 'bg-indigo-200' },
	{ id: 6, value: 'Direct Mail Letter', type: true, color: 'bg-indigo-200' },
	{ id: 7, value: 'Internet Read >>', type: true, color: 'bg-indigo-200' },
	{ id: 8, value: 'Multiline Review', type: true, color: 'bg-indigo-200' },
	{ id: 9, value: 'Networking Meeting', type: true, color: 'bg-indigo-200' },
	{ id: 10, value: 'Call In', type: true, color: 'bg-indigo-200' },
	{ id: 11, value: 'Outbound Calling', type: true, color: 'bg-indigo-200' },
	{ id: 12, value: 'Personal Visit', type: true, color: 'bg-indigo-200' },
	{ id: 13, value: 'Postcard', type: true, color: 'bg-indigo-200' },
	{ id: 14, value: 'Referral', type: true, color: 'bg-indigo-200' },
	{ id: 15, value: 'Salesperson Pilvot', type: true, color: 'bg-indigo-200' },
	{ id: 16, value: 'Sign', type: true, color: 'bg-indigo-200' },
	{ id: 17, value: 'Television', type: true, color: 'bg-indigo-200' },
	{ id: 18, value: 'Transfer', type: true, color: 'bg-indigo-200' },
	{ id: 19, value: 'Walk-In', type: true, color: 'bg-indigo-200' },
	{ id: 20, value: 'Website', type: true, color: 'bg-indigo-200' },
	{ id: 21, value: 'WebSearch', type: true, color: 'bg-indigo-200' },
	{ id: 22, value: 'Yellow Pages', type: true, color: 'bg-indigo-200' },
	{ id: 23, value: 'Other', type: true, color: 'bg-indigo-200' },
];

