export const production_multiline_header1 = [
	{value:'Sales Goal', type:false, color:''},
	{value:'Actual Sales', type:false, color:''},
	{value:'Total Premium / Dollars', type:true, color:''},
	{value:'Average Premium / Dollars', type:false, color:''},
];

export const production_multiline_header2 = [
	{value:'Actual Sales', type:false, color:''},
	{value:'Total Premium / Dollars', type:true, color:''},
	{value:'Average Premium / Dollars', type:false, color:''},
];

export const production_multiline_header3 = [
	{ id: 2, value: 'Center of Influence', type: true },
	{ id: 3, value: 'Client Request', type: true },
	{ id: 4, value: 'Direct Mail Letter', type: true },
	{ id: 5, value: 'Internet Read >>', type: true },
	{ id: 6, value: 'Multiline Review', type: true },
	{ id: 7, value: 'label', type: true },
	{ id: 8, value: 'label', type: true },
	{ id: 9, value: 'Park Bench', type: true },
	{ id: 10, value: 'Personal Visit', type: true },
	{ id: 11, value: 'Postcard', type: true },
	{ id: 12, value: 'Referral', type: true },
	{ id: 13, value: 'Salesperson Pilvot', type: true },
	{ id: 14, value: 'Sign', type: true },
	{ id: 15, value: 'Television', type: true },
	{ id: 16, value: 'Transfer', type: true },
	{ id: 17, value: 'Walk-In', type: true },
	{ id: 18, value: 'Website', type: true },
	{ id: 19, value: 'WebSearch', type: true },
	{ id: 20, value: 'Yellow Pages', type: true },
	{ id: 21, value: 'Other', type: true },
];

export const production_multiline_header4 = [
	{value:'Intitial Item Bonuses', type:false, color:''},
	{value:'Individual Target Bonuses', type:false, color:''},
	{value:'Team Target Bonuses', type:true, color:''},
	{value:'Policy Growth Bonuses', type:false, color:''},
	{value:'Lapse Rate Bonuses', type:false, color:''},
	{value:'Special Promotion', type:false, color:''},
	{value:'TOTAL BONUSES', type:false, color:''},
];

export const production_productLine_header1 = [
	{ id: 2, value: 'Average Premium', type: true, color: 'bg-green-300' },
	{ id: 3, value: 'Number of Policies', type: true, color: 'bg-green-300' },
	{ id: 4, value: 'Policy Premium', type: true, color: 'bg-green-300' },
	{ id: 5, value: 'Personally Produced', type: true, color: 'bg-yellow-500' },
	{ id: 6, value: 'Raw New', type: true, color: 'bg-yellow-500' },
	{ id: 7, value: 'Add On', type: true, color: 'bg-yellow-500' },
	{ id: 8, value: 'Transfer In', type: true, color: 'bg-yellow-500' },
	{ id: 9, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 10, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 11, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 12, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 13, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 14, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 15, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 16, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 17, value: 'Bonus', type: true, color: 'bg-yellow-500' },
];

export const production_productLine_header2 = [
	{ id: 2, value: 'Average Premium', type: true, color: 'bg-green-300' },
	{ id: 3, value: 'Number of Policies', type: true, color: 'bg-green-300' },
	{ id: 4, value: 'Center of Influence', type: true, color: 'bg-green-300' },
	{ id: 5, value: 'Client Request', type: true, color: 'bg-indigo-200' },
	{ id: 6, value: 'Direct Mail Letter', type: true, color: 'bg-indigo-200' },
	{ id: 7, value: 'Internet Read >>', type: true, color: 'bg-indigo-200' },
	{ id: 8, value: 'Multiline Review', type: true, color: 'bg-indigo-200' },
	{ id: 9, value: 'Networking Meeting', type: true, color: 'bg-indigo-200' },
	{ id: 10, value: 'Call In', type: true, color: 'bg-indigo-200' },
	{ id: 11, value: 'Outbound Calling', type: true, color: 'bg-indigo-200' },
	{ id: 12, value: 'Personal Visit', type: true, color: 'bg-indigo-200' },
	{ id: 13, value: 'Postcard', type: true, color: 'bg-indigo-200' },
	{ id: 14, value: 'Referral', type: true, color: 'bg-indigo-200' },
	{ id: 15, value: 'Salesperson Pilvot', type: true, color: 'bg-indigo-200' },
	{ id: 16, value: 'Sign', type: true, color: 'bg-indigo-200' },
	{ id: 17, value: 'Television', type: true, color: 'bg-indigo-200' },
	{ id: 18, value: 'Transfer', type: true, color: 'bg-indigo-200' },
	{ id: 19, value: 'Walk-In', type: true, color: 'bg-indigo-200' },
	{ id: 20, value: 'Website', type: true, color: 'bg-indigo-200' },
	{ id: 21, value: 'WebSearch', type: true, color: 'bg-indigo-200' },
	{ id: 22, value: 'Yellow Pages', type: true, color: 'bg-indigo-200' },
	{ id: 23, value: 'Other', type: true, color: 'bg-indigo-200' },
];

export const production_productLine_header3 = [
	// { id: 2, value: 'Average Premium', type: true, color: 'bg-green-300' },
	// { id: 3, value: 'Number of Policies', type: true, color: 'bg-green-300' },
	// { id: 4, value: 'Policy Premium', type: true, color: 'bg-green-300' },
	{ id: 5, value: 'Personally Produced', type: true, color: 'bg-yellow-500' },
	{ id: 6, value: 'Raw New', type: true, color: 'bg-yellow-500' },
	{ id: 7, value: 'Add On', type: true, color: 'bg-yellow-500' },
	{ id: 8, value: 'Transfer In', type: true, color: 'bg-yellow-500' },
	{ id: 9, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 10, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 11, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 12, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 13, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 14, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 15, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 16, value: 'label', type: true, color: 'bg-yellow-500' },
	{ id: 17, value: 'Adjustments', type: true, color: 'bg-yellow-500' },
];

export const production_productLine_header4 = [
	// { id: 2, value: 'Average Premium', type: true, color: 'bg-green-300' },
	// { id: 3, value: 'Number of Policies', type: true, color: 'bg-green-300' },
	// { id: 4, value: 'Center of Influence', type: true, color: 'bg-green-300' },
	{ id: 5, value: 'Client Request', type: true, color: 'bg-indigo-200' },
	{ id: 6, value: 'Direct Mail Letter', type: true, color: 'bg-indigo-200' },
	{ id: 7, value: 'Internet Read >>', type: true, color: 'bg-indigo-200' },
	{ id: 8, value: 'Multiline Review', type: true, color: 'bg-indigo-200' },
	{ id: 9, value: 'Networking Meeting', type: true, color: 'bg-indigo-200' },
	{ id: 10, value: 'Call In', type: true, color: 'bg-indigo-200' },
	{ id: 11, value: 'Outbound Calling', type: true, color: 'bg-indigo-200' },
	{ id: 12, value: 'Personal Visit', type: true, color: 'bg-indigo-200' },
	{ id: 13, value: 'Postcard', type: true, color: 'bg-indigo-200' },
	{ id: 14, value: 'Referral', type: true, color: 'bg-indigo-200' },
	{ id: 15, value: 'Salesperson Pilvot', type: true, color: 'bg-indigo-200' },
	{ id: 16, value: 'Sign', type: true, color: 'bg-indigo-200' },
	{ id: 17, value: 'Television', type: true, color: 'bg-indigo-200' },
	{ id: 18, value: 'Transfer', type: true, color: 'bg-indigo-200' },
	{ id: 19, value: 'Walk-In', type: true, color: 'bg-indigo-200' },
	{ id: 20, value: 'Website', type: true, color: 'bg-indigo-200' },
	{ id: 21, value: 'WebSearch', type: true, color: 'bg-indigo-200' },
	{ id: 22, value: 'Yellow Pages', type: true, color: 'bg-indigo-200' },
	{ id: 23, value: 'Other', type: true, color: 'bg-indigo-200' },
];

export const production_salesResult_wittenHeader = [
	{value:'WRITTEN', type:false, color:''},
	{value:'Auto Policies', type:true},
	{value:'Auto Premium', type:false},
	{value:'Fire Policies', type:true},
	{value:'Fire Premium', type:false},
	{value:'Life Policies', type:true},
	{value:'Life Premium', type:false},
	{value:'Health Policies', type:true},
	{value:'Health Premium', type:false},
	{value:'Bank Products', type:true},
	{value:'Bank Dollars', type:false},
	{value:'Total Products', type:true},
	{value:'Total Premium', type:false},
];
export const production_salesResult_issueHeader = [
	{value:'ISSUED', type:false, color:''},
	{value:'Auto Policies', type:true},
	{value:'Auto Premium', type:false},
	{value:'Fire Policies', type:true},
	{value:'Fire Premium', type:false},
	{value:'Life Policies', type:true},
	{value:'Life Premium', type:false},
	{value:'Health Policies', type:true},
	{value:'Health Premium', type:false},
	{value:'Bank Products', type:true},
	{value:'Bank Dollars', type:false},
	{value:'Total Products', type:true},
	{value:'Total Premium', type:false},
];